stages:
  - verify
  - sast
  - build
  - security
  - dast

runner-smoke-test:
  stage: verify
  image: alpine:3.22
  tags:
    - kubernetes
  script:
    - echo "Runner Kubernetes ShopShore opérationnel"
    - echo "Projet=$CI_PROJECT_PATH"
    - echo "Branche=$CI_COMMIT_BRANCH"
    - echo "Commit=$CI_COMMIT_SHORT_SHA"
    - uname -a
    - test -f README.md
    - test -f docker-compose.yml
    - find src -mindepth 1 -maxdepth 1 -type d | sort
    - echo "Validation initiale réussie"


build-images:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  tags:
    - kubernetes
  rules:
    - changes:
        - "src/**/*"
    - when: never
  parallel:
    matrix:
      - SERVICE:
          - accounting
          - cart
          - checkout
          - fraud-detection
          - frontend
          - frontend-proxy
          - payment
          - product-catalog
          - shipping
  script:
    - echo "Construction du microservice ${SERVICE}"
    - mkdir -p /kaniko/.docker
    - AUTH="$(printf '%s:%s' "$CI_REGISTRY_USER" "$CI_REGISTRY_PASSWORD" | base64 | tr -d '\n')"
    - printf '{"auths":{"%s":{"auth":"%s"}}}\n' "$CI_REGISTRY" "$AUTH" > /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --cache=true
      --cache-ttl=24h
      --cache-repo "${CI_REGISTRY_IMAGE}/cache"
      --context "${CI_PROJECT_DIR}/src/${SERVICE}"
      --dockerfile "${CI_PROJECT_DIR}/src/${SERVICE}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/${SERVICE}:${CI_COMMIT_SHORT_SHA}"
      --destination "${CI_REGISTRY_IMAGE}/${SERVICE}:latest"
      --registry-certificate "${CI_REGISTRY}=${CI_SERVER_TLS_CA_FILE}"

security-scan:
  stage: security
  image:
    name: aquasec/trivy:0.74.0
    entrypoint: [""]
  tags:
    - kubernetes
  rules:
    - changes:
        - "src/**/*"
    - when: never
  variables:
    TRIVY_USERNAME: "$CI_REGISTRY_USER"
    TRIVY_PASSWORD: "$CI_REGISTRY_PASSWORD"
    SSL_CERT_FILE: "$CI_SERVER_TLS_CA_FILE"
    TRIVY_CACHE_DIR: ".trivycache"
  script:
    - trivy --version
    - |
      for SERVICE in \
        accounting \
        cart \
        checkout \
        fraud-detection \
        frontend \
        frontend-proxy \
        payment \
        product-catalog \
        shipping
      do
        echo "Analyse Trivy de ${SERVICE}:${CI_COMMIT_SHORT_SHA}"

        trivy image \
          --scanners vuln \
          --severity HIGH,CRITICAL \
          --ignore-unfixed \
          --exit-code 1 \
          --format table \
          --output "trivy-${SERVICE}.txt" \
          "${CI_REGISTRY_IMAGE}/${SERVICE}:${CI_COMMIT_SHORT_SHA}"

        cat "trivy-${SERVICE}.txt"
      done
  artifacts:
    when: always
    paths:
      - trivy-*.txt
    expire_in: 1 week

sast-semgrep:
  stage: sast
  image:
    name: semgrep/semgrep:latest
    entrypoint: [""]
  tags:
    - kubernetes
  script:
    - semgrep --version
    - semgrep scan --config p/default --json --output semgrep-report.json src
    - semgrep scan --config p/default --severity ERROR --error src
  artifacts:
    when: always
    paths:
      - semgrep-report.json
    expire_in: 1 week

dast-zap:
  stage: dast
  image:
    name: ghcr.io/zaproxy/zaproxy:stable
    entrypoint: [""]
  tags:
    - kubernetes
  variables:
    DAST_TARGET_URL: "https://shopsphere.ba3s.abrdns.com"

  script:
    - echo "Analyse DAST passive de ${DAST_TARGET_URL}"
    - mkdir -p /zap/wrk
    - |
      set +e

      zap-baseline.py \
        -t "${DAST_TARGET_URL}" \
        -m 1 \
        -I \
        -r zap-report.html \
        -J zap-report.json \
        -w zap-report.md

      ZAP_EXIT=$?
      set -e

      cp /zap/wrk/zap-report.html "${CI_PROJECT_DIR}/" 2>/dev/null || true
      cp /zap/wrk/zap-report.json "${CI_PROJECT_DIR}/" 2>/dev/null || true
      cp /zap/wrk/zap-report.md "${CI_PROJECT_DIR}/" 2>/dev/null || true

      if [ "${ZAP_EXIT}" -eq 3 ]; then
        echo "Échec technique du scan ZAP"
        exit 3
      fi

      echo "Scan DAST terminé avec le code ${ZAP_EXIT}"
  artifacts:
    when: always
    paths:
      - zap-report.html
      - zap-report.json
      - zap-report.md
    expire_in: 1 week
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
