server {
    listen 8080;

    # Frontend
    location / {
        proxy_pass http://frontend:80;
    }

    # Product Catalog
    location /api/products {
        proxy_pass http://product-catalog:8080/products;
    }

    # Cart
    location /api/cart/ {
        rewrite ^/api/cart/(.*)$ /cart/$1 break;
        proxy_pass http://cart:8080;
    }

    # Checkout
    location = /api/checkout {
        proxy_pass http://checkout:8080/checkout;
    }
}

