server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/products {
        proxy_pass http://product-catalog:8080/products;
    }

    location /api/cart/ {
        rewrite ^/api/cart/(.*)$ /cart/$1 break;
        proxy_pass http://cart:8080;
    } 
    location /api/checkout {
        proxy_pass http://checkout:8080/checkout;
    }
}
